      
spring: 
    profiles: 
        active:
           - dev
---
server:
  port: 8004
  servlet:
    context-path: /provider 
mybatis:
  type-aliases-package: com.hzit.com.hzit.bean
spring:
   profiles: dev
   application:
    name: springcloud-dept		
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            
    driver-class-name: com.mysql.jdbc.Driver             
    url: jdbc:mysql://localhost:3306/bj1901         
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

logging:
  level:
    com.hzit.provider.mapper: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka 
  instance:
    instance-id: springcloud-dept-8004  
    prefer-ip-address: true 


info:
 app.name:  springcloud-dept
 company.name:  www.hzitxx.com
 build.artifactId:  $project.artifactId$
 build.version:  $project.version$
 
 
 ---
server:
  port: 8004
  servlet:
    context-path: /provider 
mybatis:
  type-aliases-package: com.hzit.com.hzit.bean
spring:
   profiles: test
   application:
    name: springcloud-dept		
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            
    driver-class-name: com.mysql.jdbc.Driver             
    url: jdbc:mysql://localhost:3306/bj1903         
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

logging:
  level:
    com.hzit.provider.mapper: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka 
  instance:
    instance-id: springcloud-dept-8004  
    prefer-ip-address: true 


info:
 app.name:  springcloud-dept
 company.name:  www.hzitxx.com
 build.artifactId:  $project.artifactId$
 build.version:  $project.version$
